version: '3.9'

services:
  api_dev:
    image: akaaua/api-ts-course
    build: .
    ports: 
      - "5000:3050"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
    
