version: '3'

services:
  api_dev:
    image: akaaua/api-ts-course
    ports: 
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
    